### PR TITLE
Ensure sdx-transform-cs meets standards

### PR DESCRIPTION
**Pull request by iwootten**
**Changes**

- Add exceptions for failure to lookup survey schemas from disk
- Add exceptions for transformation failure when performing IO operations (ZIP/PDF/Buffer creation).
- Add failure and error logging for splunk/docker

**How to test**

- Send a message with invalid survey id within to any of the transformation endpoints. Check appropriate error is logged.
- Send invalid data to any of the transform endpoints. Check appropriate error is logged.
- Send a valid message payload and check that a success message is logged.

Testing io exceptions is more difficult. Prevent write access to the /tmp directory and run a transform.

**Who can test**

Anyone but @iwootten

### CODE REVIEW

**Comment by ajmaddaford** [comment]
I can't see any tests for the new exception handling. Also, could we add the application name to the logging format in settings.py rather than every log line? This would also help to ensure it is consistently used on every log line.

**Comment by ajmaddaford** [comment]
The error messages are double quoted in the response JSON, e.g. 
```
{
  "message": "'PCK:Unsupported survey/instrument id'",
  "status": 400,
  "uri": "http://localhost:5000/pck"
}
```

**Comment by iwootten** [comment]
This was down to getting a representation of the exception passed into the default 400, 500 handlers. The case you highlighted was just a string passed in to that method. I've updated these calls to default to using ValueErrors.

**Comment by ajmaddaford** [comment]
It seems a bit unnecessary to have to wrap every error in an exception, only so the message can be pulled out with repr. What about:
```
@app.errorhandler(400)
def errorhandler_400(e):
    known_error(repr(e))

def known_error(error=None):
    app.logger.error("FAILURE:%s", error)
    message = {
        'status': 400,
        'message':error,
        'uri': request.url,
    }
    resp = jsonify(message)
    resp.status_code = 400

    return resp
```
And the same for the 500 errors. 
Also, I think `known_error` should be `client_error` and `unknown_error` should be `server_error`.

**Comment by iwootten** [comment]
Sure, I've updated this. It's unnecessary to break the server error in this way as we don't call it with strings and will only be used against flask exceptions.

**Comment by ajmaddaford** [comment]
👍

**Pull request merged**
