### PR TITLE
Import csv tests from sdx-collect

### PR DESCRIPTION
**Pull request by iwootten**
**Changes**

Bring across tests/resources from sdx-collect for the image index csv.

**How to test**

Run the unit tests and see if they pass

**Who can test**

Anyone but @iwootten

### CODE REVIEW

**Comment by ajmaddaford** [comment]
I got a test fail - it looks like it's because the expected date-time is generated in the second before the transform generated csv:
```
======================================================================
FAIL: test_transforms_csv (tests.test_transform.TestTransformService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tests/test_transform.py", line 144, in test_transforms_csv
    self.assertEqual(actual_content, expected_content)
AssertionError: '27/06/2016 17:17:49,\\\\NP3RVWAPXX370\\SDX_preprod\\EDC_QI[79 chars]01,0' != '27/06/2016 17:17:50,\\\\NP3RVWAPXX370\\SDX_preprod\\EDC_QI[79 chars]01,0'
- 27/06/2016 17:17:49,\\NP3RVWAPXX370\SDX_preprod\EDC_QImages\Images\S010000001.JPG,20160627,S010000001,023,0203,12345678901,201234,001,0
?                  ^^
+ 27/06/2016 17:17:50,\\NP3RVWAPXX370\SDX_preprod\EDC_QImages\Images\S010000001.JPG,20160627,S010000001,023,0203,12345678901,201234,001,0
?                  ^^
```

**Comment by iwootten** [comment]
Hmm. Your computer must be slow :) I guess the better route for this would be to flip the test so the time the test is run isn't the expectation, but the expectation is modified to use the test data's time.

**Comment by ajmaddaford** [comment]
The csv tests all expect a filename of EDC_023_20160312_1000.csv. I realise this works because the dates in the current json files are all 12/03/2016, but:
* If any further tests are added with different dates the tests will break
* We're not currently testing the filename

**Comment by ajmaddaford** [comment]
👍

**Pull request merged**
