### PR TITLE
Feature/integrate with sdx common

### PR DESCRIPTION
**Pull request by tundish**

### CODE REVIEW

**Comment by JamesGardiner** [comment]
@tundish - am I ok to wait until tests pass to review this?

**Comment by tundish** [comment]
Latest commit installs sdx-common from git repo as agreed. Travis builds properly and unit tests pass.

**Comment by JamesGardiner** [comment]
Closing as story cards are not ready - don't want open pull requests hanging around

**Comment by tundish** [comment]
Reopened to support sdx-common integration work. This is the client code we will use to test sdx-common deployment.

**Comment by necrophonic** [comment]
Is this still outstanding or has it been superseded by more recent common library work?

**Pull request merged**
